### ISSUE TITLE
以w开头自带HH发音

### ISSUE THREAD

**Issue by ningpengtao-coder** [yazone/g2pE_mobile#4]
python inference.py 
input_text: where
numpy input_tokens: [[25 10  7 20  7  2]] seqlens: [6] decoder_input: [[2]]
tensor input_tokens: tensor([[25, 10,  7, 20,  7,  2]], device='cuda:0') seqlens: tensor([6]) decoder_input: tensor([[2]], device='cuda:0')
predict y: tensor([[37, 70, 27, 57,  3,  3, 45, 41,  3, 66,  3, 47, 27, 48, 41,  3, 24, 50,
          3, 47]], device='cuda:0')
predict result is: HH W EH1 R

**Comment by yazone** [comment]
这个需要自己整理数据进行训练，另外where这种直接查CMU字典就好
